import { Activity, Braces, Eye, MessageSquareText, Plus, RotateCcw, Search, Send } from "lucide-react";
import { Empty, SectionHead, Status, timeAgo } from "@/components/dashboard/common";
import type { DashboardData, DashboardSubmit, EventRow } from "@/components/dashboard/types";

export function MessagesView({ data, busy, submit }: { data: DashboardData; busy: string; submit: DashboardSubmit }) {
  const appName = (id: string) => data.applications.find((app) => app.id === id)?.name || "Application";
  const availableEventTypes = Array.from(new Set([
    ...data.eventTypes.map((item) => item.name),
    ...data.endpoints.flatMap((endpoint) => endpoint.event_types),
    ...data.messages.map((message) => message.event_type)
  ])).sort();
  return <><SectionHead eyebrow="Outbound API" heading="Messages" copy="Send one event and PayloadGrid will route it to every matching endpoint." /><section className="split-layout message-layout"><form className="content-card form-card" onSubmit={(event) => submit(event, "/api/messages", (form) => ({ applicationId: form.get("applicationId"), eventType: form.get("eventType"), payload: JSON.parse(String(form.get("payload"))) }))}><h3>Send test event</h3><label>Application<select name="applicationId" required defaultValue=""><option value="" disabled>Select application</option>{data.applications.map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Event type<select name="eventType" required defaultValue=""><option value="" disabled>{availableEventTypes.length ? "Select event type" : "Add an event type first"}</option>{availableEventTypes.map((eventType) => <option key={eventType} value={eventType}>{eventType}</option>)}</select></label><label>JSON payload<textarea className="code-input" name="payload" required defaultValue={'{\n  "orderId": "order_123",\n  "status": "completed"\n}'} /></label><button className="button primary" disabled={busy === "/api/messages"}><Send size={16} /> Send message</button></form><section className="content-card table-card"><div className="card-head"><h3>Message history</h3><span>{data.messages.length} messages</span></div>{data.messages.length ? <div className="compact-list">{data.messages.map((message) => <article key={message.id}><span className="resource-icon"><MessageSquareText size={17} /></span><div><strong>{message.event_type}</strong><small>{appName(message.application_id)} · {message.id.slice(0, 8)}</small></div><Status value={message.status} /><time>{timeAgo(message.created_at)}</time></article>)}</div> : <Empty icon={<Send size={22} />} title="No outbound messages" copy="Send a test event here or use the authenticated REST API." />}</section></section></>;
}

export function DeliveriesView({ events, search, setSearch, inspect, replay, endpointName }: { events: EventRow[]; search: string; setSearch: (value: string) => void; inspect: (event: EventRow) => void; replay: (id: string) => void; endpointName: (id: string) => string }) {
  return <><SectionHead eyebrow="Observability" heading="Deliveries" copy="Search, inspect, and replay every inbound and outbound attempt." action={<div className="search-box"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search deliveries" /></div>} /><section className="content-card delivery-list">{events.length ? <div className="data-table delivery-table"><div className="table-header"><span>Event</span><span>Direction</span><span>Endpoint</span><span>Status</span><span>Response</span><span>Attempts</span><span>Time</span><span /></div>{events.map((event) => <div className="table-row" key={event.id}><span><strong>{event.event_type}</strong><small>{event.provider_event_id || event.id.slice(0, 12)}</small></span><span><i className="direction-pill">{event.direction}</i></span><span>{endpointName(event.endpoint_id)}</span><span><Status value={event.status} /></span><span>{event.response_status ? `HTTP ${event.response_status}` : event.error || "No response"}</span><span>{event.attempt_count}/{event.max_retries}</span><span>{timeAgo(event.received_at)}</span><span className="row-actions"><button className="icon-button" onClick={() => inspect(event)} title="Inspect"><Eye size={15} /></button><button className="icon-button" onClick={() => replay(event.id)} title="Replay"><RotateCcw size={15} /></button></span></div>)}</div> : <Empty icon={<Activity size={22} />} title="No matching deliveries" copy="Events appear here as soon as PayloadGrid receives or sends them." />}</section></>;
}

export function EventTypesView({ data, busy, submit }: { data: DashboardData; busy: string; submit: DashboardSubmit }) {
  return <><SectionHead eyebrow="Event catalog" heading="Event types" copy="Define the event names customers can subscribe to." /><section className="split-layout"><form className="content-card form-card" onSubmit={(event) => submit(event, "/api/event-types", (form) => ({ name: form.get("name"), description: form.get("description") }))}><h3>Add event type</h3><label>Name<input name="name" required placeholder="invoice.payment_failed" /></label><label>Description<textarea name="description" placeholder="When this event is emitted" /></label><button className="button primary" disabled={busy === "/api/event-types"}><Plus size={16} /> Save event type</button></form><section className="content-card list-card">{data.eventTypes.length ? <div className="resource-list">{data.eventTypes.map((item) => <article key={item.id}><span className="resource-icon"><Braces size={18} /></span><div><strong>{item.name}</strong><small>{item.description || "No description"}</small></div><span>{data.endpoints.filter((endpoint) => endpoint.event_types.includes(item.name)).length} subscribers</span></article>)}</div> : <Empty icon={<Braces size={22} />} title="No event types" copy="Add event types to make endpoint subscriptions easier to manage." />}</section></section></>;
}