"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { Copy, FileText, ImageUp, LoaderCircle, Plus, RotateCcw, Save, Trash2, X } from "lucide-react";
import { MarkdownContent } from "@/components/blog/markdown-content";
import { SectionHead } from "@/components/dashboard/common";

type Status = "draft" | "scheduled" | "published" | "archived";
type Post = { id: string; slug: string; title: string; excerpt: string; content_markdown: string; cover_image_url: string | null; cover_image_alt: string | null; category: string; tags: string[]; status: Status; is_featured: boolean; seo_title: string | null; seo_description: string | null; published_at: string | null; created_at: string; updated_at: string; revision_count?: number; author_name?: string | null };
type Revision = Pick<Post, "id" | "title" | "excerpt" | "content_markdown" | "cover_image_url" | "cover_image_alt" | "category" | "tags" | "status" | "is_featured" | "seo_title" | "seo_description" | "published_at" | "created_at"> & { created_by_name?: string | null };
type Draft = { id: string | null; title: string; slug: string; excerpt: string; content: string; coverImageUrl: string; coverImageAlt: string; category: string; tags: string; status: Status; isFeatured: boolean; seoTitle: string; seoDescription: string; publishedAt: string };

const starterContent = `## The problem

Explain the webhook engineering problem with concrete production context.

## Architecture

Describe the tradeoffs, failure states, and implementation decisions.

\`\`\`typescript
// Add a focused, tested example.
\`\`\`

## Operational checklist

- State what to monitor.
- Explain recovery behavior.
- Link to the relevant PayloadGrid documentation.
`;
const emptyDraft = (): Draft => ({ id: null, title: "", slug: "", excerpt: "", content: starterContent, coverImageUrl: "", coverImageAlt: "", category: "Engineering", tags: "webhooks", status: "draft", isFeatured: false, seoTitle: "", seoDescription: "", publishedAt: "" });
const localDateTime = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
const fromPost = (post: Post): Draft => ({ id: post.id, title: post.title, slug: post.slug, excerpt: post.excerpt, content: post.content_markdown, coverImageUrl: post.cover_image_url || "", coverImageAlt: post.cover_image_alt || "", category: post.category, tags: post.tags.join(", "), status: post.status, isFeatured: post.is_featured, seoTitle: post.seo_title || "", seoDescription: post.seo_description || "", publishedAt: localDateTime(post.published_at) });
const fromRevision = (revision: Revision, current: Draft): Draft => ({ id: current.id, slug: current.slug, title: revision.title, excerpt: revision.excerpt, content: revision.content_markdown, coverImageUrl: revision.cover_image_url || "", coverImageAlt: revision.cover_image_alt || "", category: revision.category, tags: revision.tags.join(", "), status: revision.status, isFeatured: revision.is_featured, seoTitle: revision.seo_title || "", seoDescription: revision.seo_description || "", publishedAt: localDateTime(revision.published_at) });

export function BlogView() {
  const [posts, setPosts] = useState<Post[]>([]); const [draft, setDraft] = useState<Draft>(emptyDraft); const [revisions, setRevisions] = useState<Revision[]>([]); const [mode, setMode] = useState<"write" | "preview">("write"); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const readingMinutes = useMemo(() => Math.max(1, Math.ceil(draft.content.trim().split(/\s+/).filter(Boolean).length / 220)), [draft.content]);
  async function load() { setLoading(true); const response = await fetch("/api/blog", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.ok) setPosts(body.posts || []); else setError(body.error || "Could not load articles"); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function select(post: Post) { setDraft(fromPost(post)); setError(""); setNotice(""); const response = await fetch(`/api/blog/${post.id}`, { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.ok) setRevisions(body.revisions || []); }
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); setBusy("save"); setError(""); const payload = { title: draft.title, slug: draft.slug || undefined, excerpt: draft.excerpt, contentMarkdown: draft.content, coverImageUrl: draft.coverImageUrl || null, coverImageAlt: draft.coverImageAlt || null, category: draft.category, tags: draft.tags.split(",").map((tag) => tag.trim()).filter(Boolean), status: draft.status, isFeatured: draft.isFeatured, seoTitle: draft.seoTitle || null, seoDescription: draft.seoDescription || null, publishedAt: draft.publishedAt ? new Date(draft.publishedAt).toISOString() : null }; const response = await fetch(draft.id ? `/api/blog/${draft.id}` : "/api/blog", { method: draft.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error || "Could not save article"); else { setNotice(draft.status === "published" ? "Article is live." : draft.status === "scheduled" ? "Article is scheduled." : "Draft saved."); await load(); if (body.post) await select(body.post); } setBusy(""); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy("upload"); setError(""); const form = new FormData(); form.set("file", file); const response = await fetch("/api/blog/upload", { method: "POST", body: form }); const body = await response.json().catch(() => ({})); if (response.ok) update("coverImageUrl", body.url); else setError(body.error || "Image upload failed"); setBusy(""); event.target.value = ""; }
  async function remove() { if (!draft.id || !window.confirm(`Delete "${draft.title}" and its revision history?`)) return; setBusy("delete"); const response = await fetch(`/api/blog/${draft.id}`, { method: "DELETE" }); if (response.ok) { setDraft(emptyDraft()); setRevisions([]); await load(); } else { const body = await response.json().catch(() => ({})); setError(body.error || "Could not delete article"); } setBusy(""); }
  function duplicate() { setDraft((current) => ({ ...current, id: null, title: `${current.title} copy`, slug: current.slug ? `${current.slug}-copy` : "", status: "draft", publishedAt: "", isFeatured: false })); setRevisions([]); setNotice("Unsaved duplicate created."); }
  function restore(revision: Revision) { setDraft((current) => fromRevision(revision, current)); setNotice("Revision loaded into the editor. Save to apply it."); window.scrollTo({ top: 0, behavior: "smooth" }); }
  return <><SectionHead eyebrow="Publishing" heading="Engineering blog" copy="Create useful webhook engineering content, preview it safely, and control exactly when it becomes public." />
    {error ? <div className="view-error">{error}<button onClick={() => setError("")}><X size={14} /></button></div> : null}{notice ? <div className="view-notice">{notice}<button onClick={() => setNotice("")}><X size={14} /></button></div> : null}
    <section className="blog-admin-layout"><aside className="content-card blog-post-list"><header><div><h3>Articles</h3><span>{posts.length}</span></div><button className="icon-button" title="New article" onClick={() => { setDraft(emptyDraft()); setRevisions([]); }}><Plus size={17} /></button></header>{loading ? <div className="blog-admin-loading"><LoaderCircle className="spin" size={20} /> Loading articles</div> : posts.length ? posts.map((post) => <button key={post.id} className={draft.id === post.id ? "active" : ""} onClick={() => void select(post)}><span><strong>{post.title}</strong><small>{post.category} · {new Date(post.updated_at).toLocaleDateString()}</small></span><em className={post.status}>{post.status}</em></button>) : <div className="blog-admin-empty"><FileText size={21} /><strong>No articles</strong><p>Start with a real engineering problem your customers search for.</p></div>}</aside>
      <form className="content-card blog-editor" onSubmit={save}><header><div><span className="section-label">{draft.id ? "Edit article" : "New article"}</span><h3>{draft.title || "Untitled draft"}</h3></div><div><button type="button" className="button secondary compact-button" disabled={!draft.title} onClick={duplicate}><Copy size={14} /> Duplicate</button><button className="button primary compact-button" disabled={Boolean(busy)}>{busy === "save" ? <LoaderCircle className="spin" size={15} /> : <Save size={15} />} Save</button></div></header><div className="blog-editor-fields"><label>Title <small>{draft.title.length}/140</small><input required minLength={4} maxLength={140} value={draft.title} onChange={(event) => update("title", event.target.value)} placeholder="How webhook retries behave under sustained failure" /></label><div className="form-row"><label>Slug<input maxLength={140} value={draft.slug} onChange={(event) => update("slug", event.target.value)} placeholder="Generated from title" /></label><label>Category<input required maxLength={60} value={draft.category} onChange={(event) => update("category", event.target.value)} /></label></div><label>Excerpt <small>{draft.excerpt.length}/320</small><textarea required minLength={20} maxLength={320} value={draft.excerpt} onChange={(event) => update("excerpt", event.target.value)} placeholder="A concise answer to the searcher's problem." /></label><div className="form-row"><label>Status<select value={draft.status} onChange={(event) => update("status", event.target.value as Status)}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Publish time<input type="datetime-local" required={draft.status === "scheduled"} value={draft.publishedAt} onChange={(event) => update("publishedAt", event.target.value)} /></label></div><label className="check-control"><input type="checkbox" checked={draft.isFeatured} onChange={(event) => update("isFeatured", event.target.checked)} /><span><strong>Feature on blog home</strong><small>Featured posts receive the primary position.</small></span></label><label>Tags <small>Comma separated</small><input value={draft.tags} onChange={(event) => update("tags", event.target.value)} placeholder="webhooks, retries, architecture" /></label></div>
        <section className="blog-cover-control"><div>{draft.coverImageUrl ? <img src={draft.coverImageUrl} alt={draft.coverImageAlt || "Cover preview"} /> : <span><ImageUp size={22} /> 16:9 cover image</span>}</div><aside className="blog-cover-fields"><div><label className="button secondary">{busy === "upload" ? <LoaderCircle className="spin" size={15} /> : <ImageUp size={15} />} {draft.coverImageUrl ? "Replace image" : "Upload image"}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={(event) => void upload(event)} /></label>{draft.coverImageUrl ? <button type="button" className="button secondary" onClick={() => { update("coverImageUrl", ""); update("coverImageAlt", ""); }}><Trash2 size={15} /> Remove</button> : null}</div>{draft.coverImageUrl ? <label>Alternative text<input required value={draft.coverImageAlt} onChange={(event) => update("coverImageAlt", event.target.value)} placeholder="Describe what the image communicates" /></label> : <p>JPEG, PNG, WebP, or GIF. Maximum 4 MB.</p>}</aside></section>
        <section className="blog-content-editor"><header><div className="segmented-control"><button type="button" className={mode === "write" ? "active" : ""} onClick={() => setMode("write")}>Write</button><button type="button" className={mode === "preview" ? "active" : ""} onClick={() => setMode("preview")}>Preview</button></div><span>{readingMinutes} min read</span></header>{mode === "write" ? <textarea className="code-input" required minLength={40} value={draft.content} onChange={(event) => update("content", event.target.value)} spellCheck /> : <MarkdownContent content={draft.content} />}</section>
        <section className="blog-seo-fields"><div><span className="section-label">Search appearance</span><h3>SEO metadata</h3></div><label>SEO title <small>{draft.seoTitle.length}/70</small><input maxLength={70} value={draft.seoTitle} onChange={(event) => update("seoTitle", event.target.value)} placeholder={draft.title || "Defaults to article title"} /></label><label>Meta description <small>{draft.seoDescription.length}/170</small><textarea maxLength={170} value={draft.seoDescription} onChange={(event) => update("seoDescription", event.target.value)} placeholder={draft.excerpt || "Defaults to excerpt"} /></label></section>
        {draft.id ? <section className="blog-revisions"><header><div><span className="section-label">Revision history</span><h3>{revisions.length} recent snapshots</h3></div><button type="button" className="button danger compact-button" disabled={Boolean(busy)} onClick={() => void remove()}><Trash2 size={14} /> Delete</button></header>{revisions.slice(0, 10).map((revision) => <article key={revision.id}><span><strong>{new Date(revision.created_at).toLocaleString()}</strong><small>{revision.created_by_name || "PayloadGrid operator"} · {revision.status}</small></span><button type="button" className="button secondary compact-button" onClick={() => restore(revision)}><RotateCcw size={13} /> Restore</button></article>)}</section> : null}
      </form></section>
  </>;
}
