import type { CSSProperties } from "react";
import { Activity, AlertTriangle, ArrowRight, Check, Eye, FileClock, Send, ShieldCheck, Zap } from "lucide-react";
import { Empty, money, SectionHead, Status, timeAgo } from "@/components/dashboard/common";
import type { DashboardData, EventRow, View } from "@/components/dashboard/types";

export function OverviewView({ data, setView, inspect, endpointName, lastRefresh }: { data: DashboardData; setView: (view: View) => void; inspect: (event: EventRow) => void; endpointName: (id: string) => string; lastRefresh: Date | null }) {
  const cards = [
    { label: "Delivery rate", value: `${data.metrics.successRate}%`, icon: ShieldCheck, tone: "green" },
    { label: "Pending queue", value: String(data.metrics.queuedEvents + data.metrics.processingEvents + data.metrics.retryingEvents), icon: Zap, tone: "blue" },
    { label: "Open incidents", value: String(data.metrics.openIncidents), icon: AlertTriangle, tone: data.metrics.openIncidents ? "red" : "green" },
    { label: "Average latency", value: `${data.metrics.avgLatency}ms`, icon: FileClock, tone: "amber" }
  ];
  const hour = new Date().getHours(); const greeting = hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening";
  return <>
    <SectionHead eyebrow="Operational overview" heading={`Good ${greeting}, ${data.context.user.name.split(" ")[0]}`} copy={`Live production activity. Last synced ${lastRefresh ? lastRefresh.toLocaleTimeString() : "now"}.`} action={<button className="button primary" onClick={() => setView("messages")}><Send size={16} /> Send event</button>} />
    <section className="metric-grid">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label}><div><span>{label}</span><strong>{value}</strong></div><i className={`metric-icon ${tone}`}><Icon size={18} /></i></article>)}</section>
    <section className="overview-grid">
      <article className="content-card health-card"><div className="card-head"><div><span className="section-label">System health</span><h3>Delivery performance</h3></div><span className={`health-label ${data.metrics.openIncidents ? "warning" : "healthy"}`}><i />{data.metrics.openIncidents ? "Needs attention" : "Healthy"}</span></div><div className="health-body"><div className="health-ring" style={{ "--health": `${data.metrics.successRate * 3.6}deg` } as CSSProperties}><span><strong>{data.metrics.successRate}%</strong><small>success</small></span></div><div className="health-stats"><div><span>Delivered</span><strong>{data.metrics.deliveredEvents}</strong></div><div><span>Queued</span><strong>{data.metrics.queuedEvents + data.metrics.processingEvents}</strong></div><div><span>Retrying</span><strong>{data.metrics.retryingEvents}</strong></div><div><span>Failed</span><strong>{data.metrics.failedEvents}</strong></div><div><span>INR revenue at risk</span><strong>{money(data.metrics.revenueAtRisk)}</strong></div></div></div></article>
      <article className="content-card setup-card"><div className="card-head"><div><span className="section-label">Quick setup</span><h3>Production checklist</h3></div></div><div className="check-list"><SetupStep done={data.applications.length > 0} number="1" title="Create an application" copy="Separate customer contexts" click={() => setView("applications")} /><SetupStep done={data.endpoints.length > 0} number="2" title="Add a destination" copy="Sign every delivery" click={() => setView("endpoints")} /><SetupStep done={data.apiKeys.some((key) => !key.revoked_at)} number="3" title="Create an API key" copy="Authenticate your server" click={() => setView("api-keys")} /></div></article>
    </section>
    <section className="content-card table-card"><div className="card-head"><div><span className="section-label">Latest activity</span><h3>Recent deliveries</h3></div><button className="text-button" onClick={() => setView("deliveries")}>View all <ArrowRight size={14} /></button></div>{data.events.length ? <div className="data-table recent-table"><div className="table-header"><span>Event</span><span>Endpoint</span><span>Status</span><span>Latency</span><span>Received</span><span /></div>{data.events.slice(0, 6).map((event) => <div className="table-row" key={event.id}><span><strong>{event.event_type}</strong><small>{event.direction}</small></span><span>{endpointName(event.endpoint_id)}</span><span><Status value={event.status} /></span><span>{event.latency_ms || 0}ms</span><span>{timeAgo(event.received_at)}</span><span><button className="icon-button" onClick={() => inspect(event)} title="Inspect delivery"><Eye size={16} /></button></span></div>)}</div> : <Empty icon={<Activity size={22} />} title="No deliveries yet" copy="Send your first message or post to an inbound endpoint to see live activity." />}</section>
  </>;
}

function SetupStep({ done, number, title, copy, click }: { done: boolean; number: string; title: string; copy: string; click: () => void }) { return <button onClick={click} className={done ? "done" : ""}><span>{done ? <Check size={15} /> : number}</span><div><strong>{title}</strong><small>{copy}</small></div><ArrowRight size={15} /></button>; }