"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowRight, LoaderCircle } from "lucide-react";
import { Brand } from "@/components/brand";

export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const search = useSearchParams(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const signup = mode === "signup"; const inviteToken = signup ? search.get("invite") || "" : "";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const values = Object.fromEntries(form.entries()); const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, inviteToken: inviteToken || undefined }) }); const payload = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) { setError(payload.error || "Could not continue"); return; } router.push("/dashboard"); router.refresh(); }
  return <main className="auth-shell"><section className="auth-aside"><Brand /><div className="auth-message"><span className="signal-label">Reliable by design</span><h1>Every event delivered. Every failure explained.</h1><p>One control plane for outbound webhooks, inbound provider callbacks, retries, signatures, and customer endpoints.</p></div><div className="delivery-path" aria-hidden="true"><span>YOUR API</span><i /><span>HOOKIN</span><i /><span>CUSTOMER</span></div></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Brand /></div><span className="section-label">{inviteToken ? "Workspace invitation" : signup ? "Start building" : "Welcome back"}</span><h2>{inviteToken ? "Join your team on HookIn" : signup ? "Create your HookIn workspace" : "Sign in to HookIn"}</h2><p>{inviteToken ? "Create your account with the invited email to join the existing workspace." : signup ? "Your first production project and application are created automatically." : "Manage your applications and webhook delivery."}</p><form onSubmit={submit}>{signup ? <label>Full name<input name="name" autoComplete="name" required minLength={2} placeholder="Jane Smith" /></label> : null}{signup && !inviteToken ? <label>Company or workspace<input name="organizationName" autoComplete="organization" required minLength={2} placeholder="Acme" /></label> : null}<label>Email address<input name="email" type="email" autoComplete="email" required placeholder="you@company.com" /></label><label>Password<input name="password" type="password" autoComplete={signup ? "new-password" : "current-password"} required minLength={signup ? 10 : 1} placeholder={signup ? "At least 10 characters" : "Your password"} /></label>{error ? <div className="form-error">{error}</div> : null}<button className="button primary wide" disabled={loading}>{loading ? <LoaderCircle className="spin" size={18} /> : null}{inviteToken ? "Join workspace" : signup ? "Create workspace" : "Sign in"}<ArrowRight size={17} /></button></form><p className="auth-switch">{signup ? "Already have an account?" : "New to HookIn?"} <Link href={signup ? "/login" : "/signup"}>{signup ? "Sign in" : "Create a workspace"}</Link></p></div></section></main>;
}