"use client";
import { type FormEvent, useEffect, useState } from "react";
import { KeyRound, Plus, RefreshCw } from "lucide-react";

type EmbeddedEndpoint = { id: string; name: string; destination_url: string; event_types: string[]; is_active: boolean };
export function EmbedEndpointManager({ token, canCreate, canSubscribe, canRotate }: { token: string; canCreate: boolean; canSubscribe: boolean; canRotate: boolean }) {
  const [endpoints,setEndpoints]=useState<EmbeddedEndpoint[]>([]); const [error,setError]=useState(""); const [secret,setSecret]=useState("");
  const headers={authorization:`Embed ${token}`,"content-type":"application/json"};
  async function load(){const response=await fetch("/api/embed/endpoints",{headers:{authorization:`Embed ${token}`},cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setEndpoints(body.endpoints||[]);}
  useEffect(()=>{void load().catch((cause)=>setError(cause.message));},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/embed/endpoints",{method:"POST",headers,body:JSON.stringify({name:form.get("name"),destinationUrl:form.get("destinationUrl"),eventTypes:String(form.get("eventTypes")||"").split(",").map(v=>v.trim()).filter(Boolean)})});const body=await response.json();if(!response.ok){setError(body.error);return;}setSecret(body.signingSecret);event.currentTarget.reset();await load();}
  async function update(endpointId:string,action:"subscriptions"|"rotate",eventTypes?:string[]){const response=await fetch("/api/embed/endpoints",{method:"PATCH",headers,body:JSON.stringify({endpointId,action,eventTypes})});const body=await response.json();if(!response.ok){setError(body.error);return;}if(body.signingSecret)setSecret(body.signingSecret);await load();}
  return <section className="embed-endpoints"><header><div><span>ENDPOINT MANAGEMENT</span><h2>Customer destinations</h2></div><button className="embed-action" onClick={()=>void load()}><RefreshCw size={13}/> Refresh</button></header>{error?<div className="embed-notice">{error}</div>:null}{secret?<div className="embed-secret"><strong>Store this signing secret now</strong><code>{secret}</code><button onClick={()=>setSecret("")}>Dismiss</button></div>:null}{canCreate?<form onSubmit={create}><input name="name" required placeholder="Endpoint name"/><input name="destinationUrl" type="url" required placeholder="https://customer.example/webhooks"/><input name="eventTypes" placeholder="order.created, invoice.paid"/><button className="embed-action"><Plus size={13}/> Add endpoint</button></form>:null}<div className="embed-endpoint-list">{endpoints.map(endpoint=><article key={endpoint.id}><div><strong>{endpoint.name}</strong><code>{endpoint.destination_url}</code></div>{canSubscribe?<input aria-label={`Subscriptions for ${endpoint.name}`} defaultValue={endpoint.event_types.join(", ")} onBlur={(event)=>void update(endpoint.id,"subscriptions",event.target.value.split(",").map(v=>v.trim()).filter(Boolean))}/>:<span>{endpoint.event_types.join(", ")||"All events"}</span>}{canRotate?<button className="embed-action" onClick={()=>void update(endpoint.id,"rotate")}><KeyRound size={13}/> Rotate secret</button>:null}</article>)}</div></section>;
}
