import { PublicPage } from "@/components/marketing/public-page";
import { LEGAL_OPERATOR_NAME, PRIVACY_EMAIL } from "@/lib/site";
import { publicMetadata } from "@/lib/seo";

export const metadata = publicMetadata({ title: "Privacy Policy", description: "How PayloadGrid collects, uses, retains, secures, and responds to requests concerning account and webhook data.", path: "/privacy" });

export default function PrivacyPage() {
  return <PublicPage eyebrow="Legal" title="Privacy Policy" intro={`Effective August 15, 2026. This notice explains how ${LEGAL_OPERATOR_NAME} processes data through PayloadGrid.`}>
    <article className="legal-copy">
      <h2>1. Roles and scope</h2><p>We act as controller or data fiduciary for account, website, security, support, and billing-administration data. For webhook payloads and customer-selected destinations, we generally act as processor or data processor on the customer's documented instructions. This policy does not replace a customer's own notice to its users.</p>
      <h2>2. Data we process</h2><p>We process names, email addresses, country codes, account type, company identity and website details, verification and legal-acceptance timestamps, authentication sessions, OAuth identifiers, workspace membership, audit activity, support communications, plan and billing status, endpoint configuration, event metadata, payloads, selected diagnostic headers, destination responses, IP-derived security signals, and delivery timing. Billing providers process payment details; PayloadGrid should not store complete card numbers or security codes.</p>
      <h2>3. Purposes and legal bases</h2><p>We use data to provide the contracted service, authenticate users, route and recover events, prevent fraud and abuse, secure infrastructure, meet legal obligations, answer support requests, and improve reliability. Depending on applicable law, processing relies on contract, legitimate uses or interests, consent, and legal obligations.</p>
      <h2>4. Data minimization</h2><p>Do not send passwords, authentication tokens, full payment-card data, health records, government identity documents, children's data, or other unnecessary sensitive data. Common authorization, cookie, token, key, secret, and signature headers are redacted from diagnostics. Projects may use transient retention to scrub terminal payload bodies immediately.</p>
      <h2>5. Retention</h2><p>Standard payload retention follows the active plan: 3 days on Free, 14 days on Starter, 30 days on Growth, and the written period for Enterprise. Delivery metadata may remain for operational and security history. Unverified accounts may be removed after the disclosed verification window and abandonment period. Account, audit, billing, and legal records are retained while needed for service, disputes, fraud prevention, accounting, or law, then deleted or anonymized.</p>
      <h2>6. Service providers and transfers</h2><p>We use vetted providers for hosting, databases, queued delivery, object storage, authentication, email, monitoring, and billing. Providers may process data in countries different from yours. Where required, we use contractual or legally recognized safeguards. We do not promise a specific data region unless it is explicitly configured and agreed.</p>
      <h2>7. Sharing and sale</h2><p>We do not sell personal data or use webhook payloads for targeted advertising. We disclose data to subprocessors as needed to run PayloadGrid, to advisers under confidentiality, during a corporate transaction, to comply with valid legal process, or to protect users and the service.</p>
      <h2>8. Security</h2><p>Controls include encrypted transport, hashed API keys, encrypted integration secrets and destination authorization headers, tenant-scoped authorization, signed deliveries, provider verification, SSRF restrictions, rate limits, audit records, and limited administrative access. No internet service can guarantee absolute security.</p>
      <h2>9. Individual rights</h2><p>Depending on location, you may request access, correction, completion, deletion, restriction, portability, objection, withdrawal of consent, information about processing, or review of an automated decision. You may also complain to the relevant regulator. If PayloadGrid processes data for a customer, we may direct the request to that customer.</p>
      <h2>10. Indian data-protection requests</h2><p>Where India's Digital Personal Data Protection framework applies, Data Principals may request access, correction, completion, erasure, and grievance handling through the contact below. Customers remain responsible for giving required notices and establishing a lawful purpose for payload data they submit.</p>
      <h2>11. Cookies</h2><p>We use essential cookies for authentication, active workspace selection, security, and session continuity. Optional analytics should run only as configured and subject to applicable consent requirements. Blocking essential cookies prevents dashboard sign-in.</p>
      <h2>12. Security incidents</h2><p>We investigate suspected breaches, contain risk, preserve evidence, and notify affected customers or authorities when required by applicable law or contract. Customers must keep their security contact current.</p>
      <h2>13. Contact and grievances</h2><p>Privacy requests and grievances may be sent to <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>. We may verify identity and authority before responding. Formal operator address and any designated grievance contact must be added before paid service opens.</p>
    </article>
  </PublicPage>;
}
