import { PublicPage } from "@/components/marketing/public-page";
import { SUPPORT_EMAIL } from "@/lib/site";
import { publicMetadata } from "@/lib/seo";

export const metadata = publicMetadata({ title: "Privacy Policy", description: "How PayloadGrid collects, uses, retains, and protects account, configuration, and webhook delivery data.", path: "/privacy" });

export default function PrivacyPage() {
  return <PublicPage eyebrow="Legal" title="Privacy Policy" intro="Effective August 1, 2026. This policy describes how PayloadGrid processes account, configuration, and webhook data.">
    <article className="legal-copy"><h2>1. Data we process</h2><p>We process account details such as name, email address, workspace membership, authentication sessions, and audit activity. To provide the webhook service, we process endpoint configuration, event metadata, webhook payloads, selected diagnostic headers, destination responses, and delivery timing.</p><h2>2. Why we process it</h2><p>We use this data to authenticate users, route and retry webhook events, verify provider requests, show delivery evidence, prevent abuse, maintain security, answer support requests, and improve the service.</p><h2>3. Sensitive data</h2><p>Do not send card numbers, CVVs, passwords, authentication tokens, health records, government identity documents, or other data that is unnecessary for event delivery. Diagnostic header capture redacts common authorization, cookie, token, key, secret, and signature headers.</p><h2>4. Retention</h2><p>Webhook payloads and captured request or response bodies are scheduled for redaction after three days under the current Free plan. Account, configuration, security, billing-related, and audit metadata may be retained while the account is active and for a reasonable period afterward where needed for security or legal obligations.</p><h2>5. Service providers</h2><p>PayloadGrid uses infrastructure providers including Vercel for application hosting, Neon for PostgreSQL storage, Upstash for queued delivery when enabled, and Resend for optional email notifications. Their processing locations follow the selected service configuration and their own terms.</p><h2>6. Sharing and sale</h2><p>We do not sell personal data. We share data with service providers only as needed to operate PayloadGrid, comply with law, prevent abuse, or protect users and the service.</p><h2>7. Security</h2><p>Implemented controls include encrypted transport, hashed API keys, encrypted provider verification secrets, tenant-scoped authorization, signed deliveries, provider signature checks, SSRF restrictions, rate limits, and audit records. No internet service can guarantee absolute security.</p><h2>8. Your choices</h2><p>You may request account access, correction, export, or deletion by contacting {SUPPORT_EMAIL}. Some audit or security records may be retained where legally permitted or operationally required.</p><h2>9. Changes</h2><p>Material policy changes will be posted here with an updated effective date. Additional data-processing terms may apply to separately agreed services.</p><h2>10. Contact</h2><p>Privacy questions can be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p></article>
  </PublicPage>;
}
