import type { FormEvent, ReactNode } from "react";

export type View = "overview" | "analytics" | "applications" | "endpoints" | "messages" | "deliveries" | "event-types" | "api-keys" | "team" | "usage" | "settings" | "workspace" | "operations" | "blog";
export type Application = { id: string; name: string; uid: string; description: string | null; created_at: string };
export type Endpoint = { id: string; application_id: string | null; name: string; provider: string; destination_url: string; signing_secret: string | null; provider_verification_required: boolean; provider_secret_hint: string | null; delivery_header_names: string[]; is_active: boolean; circuit_breaker_enabled: boolean; circuit_breaker_threshold: number; circuit_state: "closed" | "open"; circuit_opened_at: string | null; revenue_tracking_mode: "disabled" | "automatic" | "custom"; revenue_amount_path: string | null; revenue_currency_path: string | null; revenue_fixed_currency: string | null; revenue_amount_unit: "major" | "minor"; event_types: string[]; created_at: string };
export type EventRow = { id: string; endpoint_id: string; endpoint_name: string; application_id: string | null; message_id: string | null; direction: string; provider: string; provider_event_id: string | null; event_type: string; status: string; revenue_at_risk: number; revenue_currency: string | null; received_at: string; response_status: number | null; response_body: string | null; latency_ms: number | null; error: string | null; retry_count: number; max_retries: number; next_retry_at: string | null; last_error: string | null; cancelled_at: string | null; dead_lettered_at: string | null; resolved_at: string | null; resolution_note: string | null; resolved_by_name: string | null; attempt_count: number; request_headers: Record<string, unknown>; request_body: unknown; request_content_type: string; is_simulation: boolean; parent_event_id: string | null; contract_version: number | null; validation_warnings: Array<{ path: string; keyword: string; message: string }> };
export type DeliveryAttempt = { id: string; attempt_number: number; destination_url: string; request_headers: Record<string, unknown>; response_status: number | null; response_headers: Record<string, unknown>; response_body: string | null; error: string | null; latency_ms: number; created_at: string };
export type DashboardData = {
  ok: boolean; error?: string; appUrl: string; system: { queueConfigured: boolean; operator: boolean }; usage: { periodStart: string; acceptedEvents: number; limits: { messagesPerMonth: number; apiRequestsPerMinute: number; inboundRequestsPerMinute: number; endpoints: number; teamMembers: number; payloadRetentionDays: number } };
  context: { user: { id: string; name: string; email: string }; organization: { id: string; name: string; slug: string; plan: string; role: string }; organizations: Array<{ id: string; name: string; role: string }>; project: { id: string; name: string; slug: string; environment: string; payloadRetentionMode: "standard" | "transient" }; projects: Array<{ id: string; name: string; slug: string; environment: string; payloadRetentionMode: "standard" | "transient" }> };
  providers: Array<{ id: string; name: string }>;
  applications: Application[]; endpoints: Endpoint[]; events: EventRow[];
  messages: Array<{ id: string; application_id: string; event_type: string; status: string; contract_version: number | null; validation_warnings: Array<{ path: string; keyword: string; message: string }>; created_at: string }>;
  eventTypes: Array<{ id: string; application_id: string | null; name: string; description: string | null; schema: Record<string, unknown> | null; current_version: number | null; example: unknown; compatibility_mode: "backward" | "none" | null; compatibility_warnings: string[]; published_at: string | null; created_at: string }>;
  apiKeys: Array<{ id: string; name: string; key_prefix: string; scopes: string[]; last_used_at: string | null; revoked_at: string | null; created_at: string }>;
  members: Array<{ id: string; name: string; email: string; role: string; created_at: string }>;
  transformations: Array<{ id: string; name: string; event_type: string | null; config: { addFields?: Record<string, unknown>; removeFields?: string[]; renameFields?: Record<string, string>; mappings?: Array<{ from: string; to: string }> }; is_active: boolean }>;
  alerts: Array<{ id: string; name: string; channel: "email" | "slack" | "webhook"; destination: string; failure_threshold: number; window_minutes: number; is_active: boolean }>;
  alertNotifications: Array<{ id: string; event_id: string; status: string; response_status: number | null; error: string | null; created_at: string; rule_name: string; channel: string; event_type: string }>;
  auditLogs: Array<{ id: string; action: string; resource_type: string; resource_id: string | null; created_at: string }>;
  metrics: { totalEvents: number; deliveredEvents: number; failedEvents: number; retryingEvents: number; queuedEvents: number; processingEvents: number; deadLetteredEvents: number; oldestPendingAt: string | null; openIncidents: number; successRate: number; avgLatency: number; revenueAtRisk: Array<{ currency: string; amount: number | string }>; revenueTrackingEnabled: boolean; endpoints: number };
};
export type DashboardMutate = (path: string, body?: unknown, method?: string) => Promise<Record<string, unknown> | null>;
export type DashboardSubmit = (event: FormEvent<HTMLFormElement>, path: string, build: (form: FormData) => unknown, after?: (payload: Record<string, unknown>) => void) => Promise<void>;
export type EmptyProps = { icon: ReactNode; title: string; copy: string };
