import { PublicPage } from "@/components/marketing/public-page";
import { SUPPORT_EMAIL } from "@/lib/site";
import { publicMetadata } from "@/lib/seo";

export const metadata = publicMetadata({ title: "Terms of Service", description: "Terms governing access to and use of the PayloadGrid webhook delivery and management service.", path: "/terms" });

export default function TermsPage() {
  return <PublicPage eyebrow="Legal" title="Terms of Service" intro="Effective August 1, 2026. These terms govern access to and use of PayloadGrid.">
    <article className="legal-copy"><h2>1. Service</h2><p>PayloadGrid provides tools to receive, route, sign, retry, replay, and monitor webhook events. Features, limits, data handling, and availability may change as the service evolves. Your applicable plan and any separate written agreement define included capacity and service commitments.</p><h2>2. Accounts</h2><p>You are responsible for accurate registration information, access granted to workspace members, secure storage of API keys and secrets, and activity performed through your account.</p><h2>3. Acceptable use</h2><p>You may not use PayloadGrid for unlawful activity, unsolicited messaging, credential theft, malware delivery, denial-of-service activity, probing private networks, bypassing service limits, or processing data you do not have authority to process.</p><h2>4. Your data and instructions</h2><p>You retain responsibility for event payloads, destinations, provider configuration, lawful processing instructions, and customer notices. You grant PayloadGrid the limited right to process this data only to operate, secure, support, and improve the service.</p><h2>5. Reliability responsibilities</h2><p>Maintain provider-native retries and independent recovery procedures for critical payments or business operations unless a separate written agreement states otherwise. Do not use PayloadGrid as the sole system of record for source events.</p><h2>6. Limits and suspension</h2><p>Published plan limits apply per project. We may throttle or suspend traffic that threatens service stability, violates these terms, or creates security risk. We will try to contact affected users when practical.</p><h2>7. Fees</h2><p>The current Free plan has no charge. Paid capacity or services require explicit agreement. Using the Free plan does not authorize automatic billing.</p><h2>8. Disclaimer</h2><p>Except where a separate written agreement says otherwise, the service is provided on an "as available" basis to the extent permitted by law. We do not promise uninterrupted operation, fitness for a particular purpose, or that every event will be delivered.</p><h2>9. Liability</h2><p>To the extent permitted by law, PayloadGrid is not liable for indirect, incidental, special, consequential, or lost-profit damages arising from use of the service. Any separately agreed commercial liability terms take precedence for the applicable service.</p><h2>10. Contact and changes</h2><p>Questions may be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Material changes will be posted with an updated effective date.</p></article>
  </PublicPage>;
}
