import { PublicPage } from "@/components/marketing/public-page";
import { LEGAL_OPERATOR_NAME, SUPPORT_EMAIL } from "@/lib/site";
import { publicMetadata } from "@/lib/seo";

export const metadata = publicMetadata({ title: "Terms of Service", description: "Terms governing access to and use of the PayloadGrid webhook delivery and management service.", path: "/terms" });

export default function TermsPage() {
  return <PublicPage eyebrow="Legal" title="Terms of Service" intro={`Effective August 15, 2026. These terms govern your use of PayloadGrid, operated by ${LEGAL_OPERATOR_NAME}.`}>
    <article className="legal-copy">
      <h2>1. Agreement and eligibility</h2><p>By creating an account or using the service, you agree to these terms and confirm that you can enter a binding agreement for yourself or the organization you represent. If you use PayloadGrid for an organization, that organization is responsible for your use.</p>
      <h2>2. Service</h2><p>PayloadGrid provides tools to receive, route, sign, transform, retry, replay, simulate, and monitor webhook events. Your plan defines included capacity and retention. Features and limits may change prospectively; material reductions to a paid plan take effect no earlier than its next renewal unless required for security or law.</p>
      <h2>3. Accounts and security</h2><p>You are responsible for accurate personal or company information, a reachable email address, workspace permissions, destination configuration, API keys, signing secrets, and activity through your account. Notify us promptly of suspected unauthorized access. We may require time-limited email links, profile completion, or additional checks to protect the service. Email verification does not independently establish legal identity or authority to represent a company.</p>
      <h2>4. Acceptable use</h2><p>You may not use PayloadGrid for unlawful activity, unsolicited messaging, credential theft, malware, denial-of-service activity, unauthorized surveillance, prohibited content, attempts to access private networks, evasion of limits, or data you have no authority to process. You must comply with sanctions, export-control, privacy, consumer-protection, and communications laws that apply to your use.</p>
      <h2>5. Customer data</h2><p>You retain rights in your event data and remain responsible for its legality, accuracy, notices, consent, and processing instructions. You authorize us and our subprocessors to process it only to provide, secure, support, and maintain the service, comply with law, and prevent abuse. Do not send payment-card credentials, passwords, government identifiers, health data, or other sensitive data unless a written agreement explicitly permits it.</p>
      <h2>6. Plans, metering, and limits</h2><p>Accepted source events are metered according to the pricing page. Retries and individual destination attempts are not separately counted unless an order form says otherwise. We may reject, throttle, buffer, or suspend traffic that exceeds a plan, threatens stability, creates security risk, or violates these terms. We do not impose an unannounced paid overage.</p>
      <h2>7. Paid plans</h2><p>Paid plans begin only after verified checkout or a signed order form. Razorpay Standard Checkout purchases one monthly period and does not renew automatically. Access continues through the paid period. Fees are non-refundable except where required by law or for a confirmed duplicate charge. Future purchases use the price displayed when that checkout begins.</p>
      <h2>8. Taxes and billing provider</h2><p>Prices exclude applicable taxes unless stated otherwise. Razorpay processes Standard Checkout payment credentials under its terms and privacy notice; PayloadGrid does not receive complete card numbers or security codes. PayloadGrid remains responsible for its seller obligations, invoices, applicable transaction taxes, and approved refunds. You remain responsible for taxes on your own business, income, and payouts.</p>
      <h2>9. Reliability and previews</h2><p>A 202 response records acceptance, not destination delivery. Maintain provider-native retries and independent recovery procedures for critical payments or operations unless a written agreement states otherwise. Beta, preview, and simulation features may change and are not covered by a service commitment.</p>
      <h2>10. Suspension and termination</h2><p>You may stop using the service and request workspace deletion. We may suspend or terminate access for material breach, non-payment, legal requirement, abuse, or urgent security risk. Where practical, we will provide notice and an opportunity to cure. Data deletion and retention follow the Privacy Policy and applicable law.</p>
      <h2>11. Intellectual property and feedback</h2><p>PayloadGrid and its software, branding, and documentation remain ours or our licensors'. These terms grant only a limited, revocable right to use the service. You may use published SDKs under their repository licences. Feedback may be used without restriction or obligation.</p>
      <h2>12. Confidentiality</h2><p>Each party will protect non-public technical, business, and security information received from the other and use it only for the relationship. This does not cover information that is public without breach, independently developed, lawfully obtained elsewhere, or required to be disclosed by law.</p>
      <h2>13. Disclaimers and liability</h2><p>Except for written service commitments and rights that cannot legally be excluded, the service is provided as available. We do not guarantee uninterrupted delivery or fitness for a specific purpose. To the extent permitted by law, neither party is liable for indirect, special, consequential, exemplary, or lost-profit damages. Our aggregate liability for the service is limited to fees paid for the affected service during the previous 12 months; for a Free plan, the limit is US$100. This does not limit liability that law prohibits limiting.</p>
      <h2>14. Changes, notices, and disputes</h2><p>Material changes will be posted with a new effective date and, for paid users, notified through the account or email when practical. A signed order form controls where it conflicts with these terms. Governing law and forum must be stated in the checkout terms or order form before paid service begins; mandatory local consumer rights remain unaffected.</p>
      <h2>15. Contact</h2><p>Questions and legal notices may be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Formal seller identity and address will also appear at checkout before any paid transaction.</p>
    </article>
  </PublicPage>;
}
